
spring.application.name=B4_TaskManagementFrontend
server.port=8085
backend.api.url=http://localhost:8083
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false